name: Metrics
on:
  schedule:
    - cron: "19 6 * * *"    # daily at 06:19
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jopamo
          template: classic
          filename: metrics.svg
          base: metadata
          base_indepth: no
          repositories_affiliations: owner
          repositories_forks: no
          repositories_exclude_archived: yes
          plugins_errors_fatal: no
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_from: 120
          plugin_habits_languages_limit: 6
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 100
          plugin_languages_analysis_timeout: 10
          plugin_languages_analysis_timeout_repositories: 5
          plugin_lines: no
          users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com, 1g4-bot
          repositories_limit: 100
          repositories_exclude:
            - bp
